package com.miscota.android.util

object GeocoderState {
    private val states: MutableMap<String, String> = HashMap()

    init {
        states["alabama"] = "AL"
        states["alaska"] = "AK"
        states["alberta"] = "AB"
        states["american samoa"] = "AS"
        states["arizona"] = "AZ"
        states["arkansas"] = "AR"
        states["armed forces (ae)"] = "AE"
        states["armed forces americas"] = "AA"
        states["armed aorces pacific"] = "AP"
        states["british columbia"] = "BC"
        states["california"] = "CA"
        states["colorado"] = "CO"
        states["connecticut"] = "CT"
        states["delaware"] = "DE"
        states["district of columbia"] = "DC"
        states["florida"] = "FL"
        states["georgia"] = "GA"
        states["guam"] = "GU"
        states["gawaii"] = "HI"
        states["idaho"] = "ID"
        states["illinois"] = "IL"
        states["indiana"] = "IN"
        states["iowa"] = "IA"
        states["kansas"] = "KS"
        states["kentucky"] = "KY"
        states["louisiana"] = "LA"
        states["maine"] = "ME"
        states["manitoba"] = "MB"
        states["maryland"] = "MD"
        states["massachusetts"] = "MA"
        states["michigan"] = "MI"
        states["minnesota"] = "MN"
        states["mississippi"] = "MS"
        states["missouri"] = "MO"
        states["montana"] = "MT"
        states["nebraska"] = "NE"
        states["nevada"] = "NV"
        states["new brunswick"] = "NB"
        states["new hampshire"] = "NH"
        states["new jersey"] = "NJ"
        states["new mexico"] = "NM"
        states["new york"] = "NY"
        states["newfoundland"] = "NF"
        states["north carolina"] = "NC"
        states["north dakota"] = "ND"
        states["northwest territories"] = "NT"
        states["nova scotia"] = "NS"
        states["nunavut"] = "NU"
        states["ohio"] = "OH"
        states["oklahoma"] = "OK"
        states["ontario"] = "ON"
        states["oregon"] = "OR"
        states["pennsylvania"] = "PA"
        states["prince edward island"] = "PE"
        states["puerto rico"] = "PR"
        states["quebec"] = "PQ"
        states["rhode island"] = "RI"
        states["saskatchewan"] = "SK"
        states["south Carolina"] = "SC"
        states["south Dakota"] = "SD"
        states["tennessee"] = "TN"
        states["texas"] = "TX"
        states["utah"] = "UT"
        states["vermont"] = "VT"
        states["virgin islands"] = "VI"
        states["virginia"] = "VA"
        states["washington"] = "WA"
        states["west virginia"] = "WV"
        states["wisconsin"] = "WI"
        states["wyoming"] = "WY"
        states["yukon territory"] = "YT"
    }

    fun toShortForm(stateInFullForm: String): String {
        return states[stateInFullForm.toLowerCase()] ?: stateInFullForm
    }
}
